// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe3QLhYa__v57-3txGRIHI0p2mzt8-QNc',
    appId: '1:523214239733:web:5c4625bc5e6b19ca2892bc',
    messagingSenderId: '523214239733',
    projectId: 'crud-a765a',
    authDomain: 'crud-a765a.firebaseapp.com',
    storageBucket: 'crud-a765a.firebasestorage.app',
    measurementId: 'G-9S7CL0GR7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3atl3V0cj3F6FaSDRAycivIB4aZWrtyA',
    appId: '1:523214239733:android:9aefab171d8855842892bc',
    messagingSenderId: '523214239733',
    projectId: 'crud-a765a',
    storageBucket: 'crud-a765a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDLfLCH7ogJMFoYe3CUVuAaEIqRr8LnGk',
    appId: '1:523214239733:ios:a39a654a9c2ee7da2892bc',
    messagingSenderId: '523214239733',
    projectId: 'crud-a765a',
    storageBucket: 'crud-a765a.firebasestorage.app',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDLfLCH7ogJMFoYe3CUVuAaEIqRr8LnGk',
    appId: '1:523214239733:ios:a39a654a9c2ee7da2892bc',
    messagingSenderId: '523214239733',
    projectId: 'crud-a765a',
    storageBucket: 'crud-a765a.firebasestorage.app',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe3QLhYa__v57-3txGRIHI0p2mzt8-QNc',
    appId: '1:523214239733:web:20e49589e0bbbc7a2892bc',
    messagingSenderId: '523214239733',
    projectId: 'crud-a765a',
    authDomain: 'crud-a765a.firebaseapp.com',
    storageBucket: 'crud-a765a.firebasestorage.app',
    measurementId: 'G-EE4KX5483Y',
  );
}
